name: Black Duck Sca scan for Basic Users
                                                                                                                                                                                                                                         
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
                                                                                                                                                                                                                                         
jobs:
  blackduck-scan:
    runs-on: [ mac-arm-sh ]
                                                                                                                                                                                                                                         
    steps:
    
    - name: Checkout Source
      uses: actions/checkout@v4
                                                                                                                                                                                                                                         
    - name: Black Duck SCA Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        detect_args: "--detect.source.path=${{ github.workspace }}/nodejs-npm"
        ### SCANNING: Required fields
        blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
  
        ### FIX PULL REQUEST CREATION
        blackducksca_fixpr_enabled: true
        
        ### PULL REQUEST COMMENTS 
        blackducksca_prcomment_enabled: true
        ### SARIF report generation and upload to GitHub Adavanced Security
        blackducksca_reports_sarif_create: true
        blackducksca_upload_sarif_report: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
  
